paths:
  /volumes:
    post:
      summary: Upload new image
      tags: [Volume]
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                year:
                  type: number
              required: year
      responses:
        "201":
          description: Volume created successfully

    get:
      summary: Get all volumes
      tags: [Volume]
      parameters:
        - name: page
          in: query
          schema:
            type: number
            minimum: 1
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
      responses:
        "200":
          description: List of volumes retrieved successfully

  /volumes/{id}:
    get:
      summary: Get image by ID
      tags: [Volume]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        "200":
          description: Volume retrieved successfully
        "404":
          description: Volume not found

    put:
      summary: Update volume by ID
      tags: [Volume]
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                year:
                  type: number
              required: year
      responses:
        "200":
          description: Volume updated successfully
        "404":
          description: Volume not found

    delete:
      summary: Delete volume by ID
      tags: [Volume]
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        "200":
          description: Volume deleted successfully
        "404":
          description: Volume not found
